// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CardStatisticsVertical: typeof import('./src/@core/components/CardStatisticsVertical.vue')['default']
    ErrorHeader: typeof import('./src/@core/components/ErrorHeader.vue')['default']
    Icons: typeof import('./src/@core/components/Icons.vue')['default']
    IconWrapper: typeof import('./src/@core/components/IconWrapper.vue')['default']
    Modal: typeof import('./src/@core/components/Modal.vue')['default']
    Recursos: typeof import('./src/@core/components/Recursos.vue')['default']
    RightPanel: typeof import('./src/@core/components/RightPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
  }
}
